# TODO Certs

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-prod-mattermost
spec:
  secretName: $CERT_SECRET_NAME
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io
  commonName: "mattermost.${SHARINGIO_PAIR_BASE_DNS_NAME}"
  dnsNames:
    - "mattermost.${SHARINGIO_PAIR_BASE_DNS_NAME}"
