apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configuration.yaml
  - statefulset.yaml
  - service-account.yaml
  - cluster-role-binding.yaml
  - tilt-service.yaml
configMapGenerator:
- name: kubemacs-configuration
  behavior: merge
  literals:
  - TZ=Pacific/Auckland
  - GIT_EMAIL=ii@ii.coop
  - GIT_NAME=Hippie Hopper
  - INIT_ORG_FILE=~/apisnoop/deployments/k8s/xip.io/README.org:37
# configMapGenerator:
#   - name: kubemacs-options
#     env: kubemacs-options
