# Install Postgresql-HA
# #+name: postgres-database

apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: mattermost-db
spec:
  enableConnectionPooler: true
  connectionPooler:
    mode: session
    resources:
      requests:
        cpu: 250m
        memory: 100Mi
      limits:
        cpu: "1"
        memory: 100Mi
  teamId: "mattermost"
  volume:
    size: 50Gi
  numberOfInstances: 3
  users:
    mattermost:  # database owner
    - superuser
    - createdb
  databases:
    mattermost: mattermost  # dbname: owner
  postgresql:
    version: "13"
