

# #+NAME: Metrics-Server

apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: kube-system
spec:
  releaseName: metrics-server
  chart:
    repository: https://olemarkus.github.io/metrics-server
    name: metrics-server
    version: 2.11.2
  values:
    args:
      - --logtostderr
      - --kubelet-preferred-address-types=InternalIP
      - --kubelet-insecure-tls
