apiVersion: metal.sidero.dev/v1alpha1
kind: ServerClass
metadata:
  name: raspberrypi4-servers
spec:
  environmentRef:
    name: raspberrypi4-servers
  configPatches:
    - op: add
      path: /cluster/allowSchedulingOnMasters
      value: true
    - op: replace
      path: /machine/install
      value:
        disk: /dev/mmcblk1
        image: ghcr.io/talos-systems/installer:v0.10.3
        bootloader: true
        wipe: false
        force: false
  qualifiers:
    cpu:
      - manufacturer: Broadcom
        version: "BCM2711 (ARM Cortex-A72)"
    systemInformation:
      - manufacturer: "Raspberry Pi Foundation"
        productName: "Raspberry Pi 4 Model B"
