#+HUGO_BASE_DIR: ./
#+HUGO_SECTION: ./post
#+HUGO_WEIGHT: auto
#+HUGO_AUTO_SET_LASTMOD: t
* Welcome to the blog scroll!  Wanna contribute? Read this first!
This org file contains all the blog posts published to [[https://blog.ii.coop]].
** About the Blog
Our blog is made with [[https://gohugo.io][hugo]], a static site generator.  All necessary code and content for the site are contained in this ~/blog~ directory.
Hugo parses the markdown files contained in [[file:content/][/content]] , with all our blog posts held in [[file:content/posts/][/content/posts]].

NOTE: While hugo can also parse org, we felt it best to use the syntax it is designed for.

We generate our markdown with [[file:~/humacs/doom-emacs/modules/lang/org/README.org::*Module Flags][org-export]].  This is done intentionally from within this file.  After exporting a blog article, you can commit and push your changes to see it go live after a minute or two at blog.ii.coop.

** Adding a new blog post
This file is organized by categories, like [[Guides]] and [[News]].  To add a new blog post, create a newline beneath a category heading, then type ~<blog~ and hit ~TAB~.  This will trigger our blog snippet, running through all the fields necessary.

Fill out the field, press tab to move to the next one, until you reach the line below properties.  Then, you can either just start typing your blog /or/ you can include an org file in our org repo with this code block
: #+include: ../relative/path/to/file.org

** Marking the blog post as a draft
If you are not yet ready to publish, you can mark the blog heading with =TODO= and, even if it's exported, it will be marked as a draft.  Remove the TODO when it's ready to go live!
** Exporting blog posts from this org scroll
You can either export all the blogs in this file or an individual piece.
*** Exporting an individual blog
Navigate to the blog post, and iwth your point somewhere in that post hit ~,eHH~.  This is an org dispatch to Hugo with option `export subtree or file to .md file`.  This will create, or overwrite if it exists, a markdown file in [[file:content/posts/][content/posts]] named whatever is set in the blogs property drawer.  Tags, category, draft status, author, summary, etc. all come over.
*** Exporting all the blogs
Anywhere in the file hit ~,eHA~.  This will create, or overwrite if it exists, markdown files in content/posts for every blog post with a proper property drawer, each named what's set in that drawer.
** That's it! enjoy!!
Though if i missed something, or it's confusing, lemme know!
* Guides :@guides:
** Deploying Talos to Equinix                                                                                           :kubernetes:equinix:talos:org:
:PROPERTIES:
:EXPORT_FILE_NAME: deplying-talos-to-equinix
:EXPORT_DATE: 2021-02-03
:EXPORT_HUGO_MENU: :menu "main"
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :summary "From nodes to workloads on baremetal"
:END:
#+include: "../ii/equinix-metal-capi-talos-kubernetes/README.org"
** TODO New Contributor Summit Session 01                                                                                     :kubernetes:ncw:testing:
:PROPERTIES:
:EXPORT_FILE_NAME: new-contributor-summit-session-01
:EXPORT_DATE: 2021-02-05
:EXPORT_HUGO_MENU: :menu "main"
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :summary "Intro to Testing for new K8s contributors"
:END:
#+include: ../ncw/session-01.org
** TODO New Contributor Summit Session 02                                                                                 :kubernetes:ncw:testing:org:
:PROPERTIES:
:EXPORT_FILE_NAME: new-contributor-summit-session-02
:EXPORT_DATE: 2021-02-05
:EXPORT_HUGO_MENU: :menu "main"
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :summary "Part Two to our intro to testing for new K8s contributors"
:END:
#+include: ../ncw/session-02.org
** TODO New Contributor Summit Session 03                                                                                 :kubernetes:ncw:testing:org:
:PROPERTIES:
:EXPORT_FILE_NAME: new-contributor-summit-session-03
:EXPORT_DATE: 2021-02-05
:EXPORT_HUGO_MENU: :menu "main"
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :summary "Part Three to our intro to testing for new K8s contributors"
:END:
#+include: ../ncw/session-03.org
* News :@news:org
