

# Certs

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: kanban-ii-coop
spec:
  acme:
    email: kanban@ii.coop
    preferredChain: ""
    privateKeySecretRef:
      name: letsencrypt-prod
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - http01:
        ingress:
          class: nginx
      selector:
        dnsNames:
        - kanban.ii.coop
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kanban-ii-coop
  namespace: kanban-ii-coop
spec:
  dnsNames:
  - kanban.ii.coop
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: kanban-ii-coop
  secretName: letsencrypt-prod
