kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
 - role: control-plane
   extraPortMappings:
   - containerPort: 67
     hostPort: 67
     protocol: UDP
   - containerPort: 69
     hostPort: 69
     protocol: UDP
   - containerPort: 80
     hostPort: 80
     protocol: TCP
   - containerPort: 443
     hostPort: 443
     protocol: TCP
   - containerPort: 4011
     hostPort: 4011
     protocol: UDP
   - containerPort: 7472
     hostPort: 7472
     protocol: UDP
   - containerPort: 8081
     hostPort: 8081
     protocol: TCP
   kubeadmConfigPatches:
   - |
     apiVersion: kubeadm.k8s.io/v1beta2
     kind: InitConfiguration
     nodeRegistration:
       kubeletExtraArgs:
         node-labels: "ingress-ready=true"
